FROM node:18 AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm run build



FROM node:18-slim

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./

CMD [ "npm", "run", "server" ]